name: 'pipeline-v1'

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile-Deploy.dockerfile'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Notify'
        run: echo "Deploying"

      - name: 'Pulling code'
        uses: actions/checkout@v4

      - name: 'Login Docker Hub'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'Build image'
        run: docker build -f Dockerfile-Deploy.dockerfile -t ${{ secrets.DOCKER_USERNAME }}/devops:latest .

      - name: 'Push image to Docker Hub'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops:latest

      - name: 'On failure'
        if: failure()
        run: echo "Push image to Docker Hub failure!"

      - name: 'On success'
        if: success()
        run: echo "Push image to Docker Hub success!"
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 'Notify'
        run: echo "Deploying"
